### ISSUE TITLE
Graphics Bug when getting sticker inside of Duty

### ISSUE THREAD

**Issue by Hukinator** [MidoriKami/EzWondrousTails#19] opened 2024-11-26 22:22 UTC
Hey i was completing The Binding Coil of Bahamut turn 5 unsync and before leaving the duty i opened the Book and clicked on the duty to get the sticker. It stays looking like that (screenshot below) even when reopening the Book inside the duty. As soon as I left the duty and opened the book again, it was gone. The only logs it gave me was this:

23:06:17.231 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 167
23:06:17.231 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 170
23:06:17.231 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 171
23:06:17.256 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 167
23:06:17.256 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 170
23:06:17.256 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 171
23:06:18.757 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 167
23:06:18.757 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 170
23:06:18.757 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 171
23:06:18.767 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 167
23:06:18.767 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 170
23:06:18.767 | INF | [WondrousTailsSolver] [WondrousTails] Unrecognized ID: 171

![image_2024-11-26_230835890](https://github.com/user-attachments/assets/50bb307f-dc92-4c0f-b00b-87b30bac7824)

**Comment by MidoriKami** [comment] 2024-11-27 00:40
Duplicate/Related to #18

**Comment by MidoriKami** [comment] 2024-11-27 00:47
What is your UI texture resolution set to in your graphics settings? Please post a pic.

**Comment by MidoriKami** [comment] 2024-11-27 01:23
Also, it's not quite a bug, it's to show you that the duty you are currently in counts as that task. It's rendering incorrectly though.

**Comment by katawajojo** [comment] 2024-11-27 03:48
Yeah, it looks like it regressed back to how it was when #17 was reported

I can try to fix it and make a pull request

**Comment by MidoriKami** [comment] 2024-11-27 04:27
It could be this code not correctly reading your UI texture resolution setting? 
(Note, this has absolutely nothing to do with 4k displays or 4k resolution in the screen configuration. This setting is internal texture quality. Default icon texture size is 32x32, HQ is 64x64. Again, this doesn't effect the physical size of any UI elements.)
https://github.com/MidoriKami/KamiToolKit/blob/master/Classes/Part.cs#L60-L86

I checked in the debug tools that the texture coordinate and texture size is correct
![image](https://github.com/user-attachments/assets/1a90bfc9-57ae-4da4-9c7d-7447216c56c4)

It should use Standard Resolution coordinates and size, and if you have 4k textures enabled then it scales up the coordinates.

**Comment by Hukinator** [comment] 2024-11-27 05:37
Hey don't know if it's still needed but i think this is the setting you mentioned right?
![image](https://github.com/user-attachments/assets/20be1313-08e8-463a-997e-a69866ab682d)

**Comment by MidoriKami** [comment] 2024-11-27 06:19
Yeah that's the one I was looking for. I'll have to check that the function I use still gives a value of 2, when using High quality textures.

**Comment by MidoriKami** [comment] 2024-11-28 02:37
I have confirmed that the above setting is being determined correctly, does this texture issue occur on both High and Low resolution settings? (A game restart is required to switch the setting)

**Comment by totallyskelebones** [comment] 2024-11-28 22:31
Hi! I am experiencing the same issue as the other user. I use the same settings as them and tried the option you mention and it still has the same (or a similar) issue. It seems to be reversed and is showing a small ui when set to big and vice versa. 
(Screenshot of what it looks like currently after adjusting ui resolution:)
![ffxiv_dx11_hmI0HI66Ee](https://github.com/user-attachments/assets/1cfc8a9f-4f99-4ebd-ad2c-0b2fe689229a)

**Comment by MidoriKami** [comment] 2024-11-29 00:10
Resolved via
https://github.com/MidoriKami/KamiToolKit/commit/2acff97db3fa146fbb47fe1768bbf07821e6b743
https://github.com/MidoriKami/KamiToolKit/commit/515d12187a0e0373fce9f155c906b950433d98f5

**Closed as completed by MidoriKami** 2024-11-29 00:10 UTC
Labels: bug
